@startuml
title C4 Level 2 - Container Diagram\nMeeting Room Booking System

top to bottom direction

skinparam linetype ortho
skinparam nodesep 70
skinparam ranksep 60
skinparam rectangle {
    Padding 15
}

actor "Employee" as Employee
actor "Administrator" as Admin

Employee -[hidden]right-> Admin

rectangle "Meeting Room Booking System" {
    rectangle "Web Frontend\nHTML / CSS / JavaScript" as Frontend
    rectangle "Backend API\nFastAPI" as Backend

    rectangle "Outbox Publisher\nPython worker" as Publisher
    queue "RabbitMQ" as RabbitMQ
    rectangle "Email Worker\nPython worker" as Worker

    Backend -[hidden]right-> Publisher
}

database "PostgreSQL\nNeon" as DB
rectangle "Email Provider\nUniSender / SMTP" as Email <<External System>>

Employee -down-> Frontend
Admin -down-> Frontend
Frontend -right-> Backend : REST
Backend -down-> DB : SQL

Publisher -down-> DB
Publisher -right-> RabbitMQ
RabbitMQ -right-> Worker
Worker -right-> Email

Backend -down-> Email

@enduml
